// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::D12, // IGN 1
	Gpio::D13, // IGN 2
	Gpio::E14, // INJ 1
	Gpio::E13, // INJ 2
	Gpio::D8, // FP
	Gpio::E5, // TACH
	Gpio::B14, // ALED
	Gpio::B15, // WLED
// "IGN 1",
// "IGN 2",
// "INJ 1",
// "INJ 2",
// "FP",
// "TACH",
// "ALED",
// "WLED",
}
